### ISSUE TITLE
update welcome page

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#554]
The welcome page can be improved namely;

- The cryptopower logo should be added to the content of the page
- the should be a back button at the top left to go back to the previous step

![Screenshot from 2024-06-24 09-01-03](https://github.com/crypto-power/cryptopower/assets/25265396/40d50004-d567-47fe-b084-5e88abc432b7)

**Comment by ademuanthony** [comment]
I am working on this

**Comment by ademuanthony** [comment]
> I am working on this

Sorry, I wasn’t fast enough here. It is because I am trying to understand the codebase. I was already doing something though, but I can see that another PR has addressed this issue. I will move to another one.
<img width="802" alt="image" src="https://github.com/user-attachments/assets/d8ea4f67-77ad-4dde-8cf7-2317e68af208">
